### ISSUE TITLE
Dataset question: Possible to generate UNI image using INV1 and INV2

### ISSUE THREAD

**Issue by mathieuboudreau** [JosePMarques/MP2RAGE-related-scripts#1]
Hi Jose,

In the dataset your provide in your repo, I'm assuming that the UNI image is the already S_MP2RAGE (eq. 1 & 2) using the INV1 and INV2 datasets you also provided, however is it possible to recalculate UNI from these two inversion images you provided? Since these are magnitude images, I'm assuming that some time of polarity inversion would be required before doing the standard MP2RAGE algebraic calculation, so was UNI simply an output of the scanner and can't be re-calculated offline using the data you provided?

**Comment by mathieuboudreau** [comment]
I guess a better question would be: are those datasets truly magnitude, or are they "real" and need a conversion factor to recalibrate the positive integer values to +- real values, and what would that conversion be? Something like (data-4095)/(constant)?

**Comment by JosePMarques** [comment]
Hi Mathieu,


Both datasets are magnitude which is what most scanners will give you, in Siemens the combination into the uni image is done on the complex data prior to coil combination. So, you wouldn't actually be able to compute the UNI/MP2RAGE out of them because you are indeed lacking the polarity.


On the other hand, you could using, the uni Image estimate the polarity of the INV1 image. Whenever the UNI/MP2RAGE is negative (which in the SIEMENS DICOM world is <4095/2) the INV1 should be negative. In practice This INV1 with the added phase and INV2phase wouldn't be able to compute the UNI image because they are both sum of squares images. Thus a better estimation of the INV1 image (one that is consistent with INV2 and UNI) is done inside the function RobustCombination.m


Hope this helps, José


________________________________
